#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: mysecretpassword
#  jpa:
#    hibernate:
#      ddl-auto: update
#  database-platform: org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    spring:
      jpa:
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

secret:
  key: "secretsecretsecret-??6==_=#RngHeR8~;Fbxd/]jm4J6tZ2=?X#8;Q3#fGOAf%=5zB1gHcf2]H%0K4NamyF&5B4^c_HV])PP#eGce]wL=secretsecretsecret"